apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations:
    getambassador.io/resource-changed: 'true'
  managedFields:
    - apiVersion: getambassador.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:getambassador.io/resource-changed': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          .: {}
          'f:prefix': {}
          'f:service': {}
      manager: kubectl
      operation: Update
      time: '2021-07-14T00:33:01Z'
  name: guestbook-ui
  namespace: default
spec:
  prefix: /guestbook-ui /
  service: guestbook-ui
